name: Submit

on:
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    env:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest

      - name: Run Script
        env:
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}
          RUN_ID_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: python submit.py
